// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_state.sql

package store

import (
	"context"
)

const getAppState = `-- name: GetAppState :one
SELECT value
FROM app_state
WHERE key = ?
`

func (q *Queries) GetAppState(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppState, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setAppState = `-- name: SetAppState :exec
INSERT INTO app_state (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (key) DO UPDATE SET value      = excluded.value,
                                updated_at = excluded.updated_at
`

type SetAppStateParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

// SetAppState is the raw half of SetFlag; call that instead, since the previous
// value is the part callers actually need and this does not return it.
func (q *Queries) SetAppState(ctx context.Context, arg SetAppStateParams) error {
	_, err := q.db.ExecContext(ctx, setAppState, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
