// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package store

import (
	"context"
	"database/sql"
)

const findSnapshotByToken = `-- name: FindSnapshotByToken :one
SELECT id, recipient_id, digest_date, token, events, created_at, notified_at
FROM digest_snapshots
WHERE token = ?
`

func (q *Queries) FindSnapshotByToken(ctx context.Context, token string) (DigestSnapshots, error) {
	row := q.db.QueryRowContext(ctx, findSnapshotByToken, token)
	var i DigestSnapshots
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.DigestDate,
		&i.Token,
		&i.Events,
		&i.CreatedAt,
		&i.NotifiedAt,
	)
	return i, err
}

const getSnapshotForDate = `-- name: GetSnapshotForDate :one
SELECT id, recipient_id, digest_date, token, events, created_at, notified_at
FROM digest_snapshots
WHERE recipient_id = ?
  AND digest_date = ?
`

type GetSnapshotForDateParams struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
}

func (q *Queries) GetSnapshotForDate(ctx context.Context, arg GetSnapshotForDateParams) (DigestSnapshots, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotForDate, arg.RecipientID, arg.DigestDate)
	var i DigestSnapshots
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.DigestDate,
		&i.Token,
		&i.Events,
		&i.CreatedAt,
		&i.NotifiedAt,
	)
	return i, err
}

const insertSnapshotIfAbsent = `-- name: InsertSnapshotIfAbsent :execrows
INSERT INTO digest_snapshots (recipient_id, digest_date, token, events, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (recipient_id, digest_date) DO NOTHING
`

type InsertSnapshotIfAbsentParams struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
	Token       string `json:"token"`
	Events      string `json:"events"`
	CreatedAt   string `json:"created_at"`
}

// InsertSnapshotIfAbsent is half of UpsertSnapshot; call that rather than this.
// DO NOTHING plus a re-read, instead of catching the uniqueness violation,
// because the row the loser wants is the one the winner wrote.
// The affected-row count is the only exact answer to "did this call write it":
// comparing created_at would call a second attempt within the same second a
// fresh insert.
func (q *Queries) InsertSnapshotIfAbsent(ctx context.Context, arg InsertSnapshotIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSnapshotIfAbsent,
		arg.RecipientID,
		arg.DigestDate,
		arg.Token,
		arg.Events,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listSnapshotKeysSince = `-- name: ListSnapshotKeysSince :many
SELECT recipient_id, digest_date
FROM digest_snapshots
WHERE digest_date >= ?
ORDER BY digest_date, recipient_id
`

type ListSnapshotKeysSinceRow struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
}

// ListSnapshotKeysSince tells the due check which digests are already done.
// Keys only: the events column holds a whole day of calendar data per row and
// the check has no use for it.
func (q *Queries) ListSnapshotKeysSince(ctx context.Context, digestDate string) ([]ListSnapshotKeysSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotKeysSince, digestDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotKeysSinceRow{}
	for rows.Next() {
		var i ListSnapshotKeysSinceRow
		if err := rows.Scan(&i.RecipientID, &i.DigestDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeSnapshotsBefore = `-- name: PurgeSnapshotsBefore :execrows
DELETE
FROM digest_snapshots
WHERE digest_date < ?
`

func (q *Queries) PurgeSnapshotsBefore(ctx context.Context, digestDate string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSnapshotsBefore, digestDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNotifiedAt = `-- name: SetNotifiedAt :execrows
UPDATE digest_snapshots
SET notified_at = ?
WHERE id = ?
  AND notified_at IS NULL
`

type SetNotifiedAtParams struct {
	NotifiedAt sql.NullString `json:"notified_at"`
	ID         int64          `json:"id"`
}

// SetNotifiedAt is the raw half of MarkNotified; call that instead. The
// IS NULL guard is what keeps the timestamp on the first channel that got
// through: every enabled target calls this, and without it the last one to
// succeed would overwrite the first.
func (q *Queries) SetNotifiedAt(ctx context.Context, arg SetNotifiedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNotifiedAt, arg.NotifiedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
