// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package store

import (
	"context"
	"database/sql"
)

const findSnapshotByToken = `-- name: FindSnapshotByToken :one
SELECT id, recipient_id, digest_date, token, events, created_at, notified_at
FROM digest_snapshots
WHERE token = ?
`

func (q *Queries) FindSnapshotByToken(ctx context.Context, token string) (DigestSnapshots, error) {
	row := q.db.QueryRowContext(ctx, findSnapshotByToken, token)
	var i DigestSnapshots
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.DigestDate,
		&i.Token,
		&i.Events,
		&i.CreatedAt,
		&i.NotifiedAt,
	)
	return i, err
}

const getSnapshotForDate = `-- name: GetSnapshotForDate :one
SELECT id, recipient_id, digest_date, token, events, created_at, notified_at
FROM digest_snapshots
WHERE recipient_id = ?
  AND digest_date = ?
`

type GetSnapshotForDateParams struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
}

func (q *Queries) GetSnapshotForDate(ctx context.Context, arg GetSnapshotForDateParams) (DigestSnapshots, error) {
	row := q.db.QueryRowContext(ctx, getSnapshotForDate, arg.RecipientID, arg.DigestDate)
	var i DigestSnapshots
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.DigestDate,
		&i.Token,
		&i.Events,
		&i.CreatedAt,
		&i.NotifiedAt,
	)
	return i, err
}

const replaceSnapshotEvents = `-- name: ReplaceSnapshotEvents :execrows
UPDATE digest_snapshots
SET events = ?,
    created_at = ?,
    notified_at = NULL
WHERE recipient_id = ?
  AND digest_date = ?
`

type ReplaceSnapshotEventsParams struct {
	Events      string `json:"events"`
	CreatedAt   string `json:"created_at"`
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
}

// ReplaceSnapshotEvents is the raw operator-refresh write. Scheduled captures
// must use UpsertSnapshot instead so old snapshots remain unchanged.
func (q *Queries) ReplaceSnapshotEvents(ctx context.Context, arg ReplaceSnapshotEventsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, replaceSnapshotEvents,
		arg.Events,
		arg.CreatedAt,
		arg.RecipientID,
		arg.DigestDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSnapshotIfAbsent = `-- name: InsertSnapshotIfAbsent :execrows
INSERT INTO digest_snapshots (recipient_id, digest_date, token, events, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (recipient_id, digest_date) DO NOTHING
`

type InsertSnapshotIfAbsentParams struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
	Token       string `json:"token"`
	Events      string `json:"events"`
	CreatedAt   string `json:"created_at"`
}

// InsertSnapshotIfAbsent is half of UpsertSnapshot; call that rather than this.
// DO NOTHING plus a re-read, instead of catching the uniqueness violation,
// because the row the loser wants is the one the winner wrote.
// The affected-row count is the only exact answer to "did this call write it":
// comparing created_at would call a second attempt within the same second a
// fresh insert.
func (q *Queries) InsertSnapshotIfAbsent(ctx context.Context, arg InsertSnapshotIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSnapshotIfAbsent,
		arg.RecipientID,
		arg.DigestDate,
		arg.Token,
		arg.Events,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLatestSnapshots = `-- name: ListLatestSnapshots :many
SELECT id, recipient_id, digest_date, token, created_at, notified_at
FROM digest_snapshots s
WHERE digest_date = (SELECT MAX(digest_date)
                     FROM digest_snapshots
                     WHERE recipient_id = s.recipient_id)
`

type ListLatestSnapshotsRow struct {
	ID          int64          `json:"id"`
	RecipientID int64          `json:"recipient_id"`
	DigestDate  string         `json:"digest_date"`
	Token       string         `json:"token"`
	CreatedAt   string         `json:"created_at"`
	NotifiedAt  sql.NullString `json:"notified_at"`
}

// ListLatestSnapshots gives the home page each recipient's most recent captured
// day. The correlated subquery, rather than a window function, so the
// UNIQUE(recipient_id, digest_date) index answers it directly.
// The events column is excluded: it holds a whole day of calendar per row and
// an overview has no use for it.
func (q *Queries) ListLatestSnapshots(ctx context.Context) ([]ListLatestSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestSnapshotsRow{}
	for rows.Next() {
		var i ListLatestSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.DigestDate,
			&i.Token,
			&i.CreatedAt,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotKeysSince = `-- name: ListSnapshotKeysSince :many
SELECT recipient_id, digest_date
FROM digest_snapshots
WHERE digest_date >= ?
ORDER BY digest_date, recipient_id
`

type ListSnapshotKeysSinceRow struct {
	RecipientID int64  `json:"recipient_id"`
	DigestDate  string `json:"digest_date"`
}

// ListSnapshotKeysSince tells the due check which digests are already done.
// Keys only: the events column holds a whole day of calendar data per row and
// the check has no use for it.
func (q *Queries) ListSnapshotKeysSince(ctx context.Context, digestDate string) ([]ListSnapshotKeysSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshotKeysSince, digestDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotKeysSinceRow{}
	for rows.Next() {
		var i ListSnapshotKeysSinceRow
		if err := rows.Scan(&i.RecipientID, &i.DigestDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnnotifiedSnapshotsBefore = `-- name: ListUnnotifiedSnapshotsBefore :many
SELECT id, recipient_id, digest_date, token, created_at, notified_at
FROM digest_snapshots
WHERE notified_at IS NULL
  AND created_at < ?
ORDER BY created_at
`

type ListUnnotifiedSnapshotsBeforeRow struct {
	ID          int64          `json:"id"`
	RecipientID int64          `json:"recipient_id"`
	DigestDate  string         `json:"digest_date"`
	Token       string         `json:"token"`
	CreatedAt   string         `json:"created_at"`
	NotifiedAt  sql.NullString `json:"notified_at"`
}

// ListUnnotifiedSnapshotsBefore finds digests that were captured and then
// reached nobody. Every enabled target failing leaves the row exactly like
// this, and it is otherwise silent: nothing else in the app notices.
func (q *Queries) ListUnnotifiedSnapshotsBefore(ctx context.Context, createdAt string) ([]ListUnnotifiedSnapshotsBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnnotifiedSnapshotsBefore, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnnotifiedSnapshotsBeforeRow{}
	for rows.Next() {
		var i ListUnnotifiedSnapshotsBeforeRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.DigestDate,
			&i.Token,
			&i.CreatedAt,
			&i.NotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeSnapshotsBefore = `-- name: PurgeSnapshotsBefore :execrows
DELETE
FROM digest_snapshots
WHERE digest_date < ?
`

func (q *Queries) PurgeSnapshotsBefore(ctx context.Context, digestDate string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSnapshotsBefore, digestDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNotifiedAt = `-- name: SetNotifiedAt :execrows
UPDATE digest_snapshots
SET notified_at = ?
WHERE id = ?
  AND notified_at IS NULL
`

type SetNotifiedAtParams struct {
	NotifiedAt sql.NullString `json:"notified_at"`
	ID         int64          `json:"id"`
}

// SetNotifiedAt is the raw half of MarkNotified; call that instead. The
// IS NULL guard is what keeps the timestamp on the first channel that got
// through: every enabled target calls this, and without it the last one to
// succeed would overwrite the first.
func (q *Queries) SetNotifiedAt(ctx context.Context, arg SetNotifiedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNotifiedAt, arg.NotifiedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
