// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package store

import (
	"context"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO notification_targets (recipient_id, kind, config, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, recipient_id, kind, config, enabled
`

type CreateTargetParams struct {
	RecipientID int64  `json:"recipient_id"`
	Kind        string `json:"kind"`
	Config      string `json:"config"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (NotificationTargets, error) {
	row := q.db.QueryRowContext(ctx, createTarget,
		arg.RecipientID,
		arg.Kind,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationTargets
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Config,
		&i.Enabled,
	)
	return i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE
FROM notification_targets
WHERE id = ?
`

func (q *Queries) DeleteTarget(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTarget, id)
	return err
}

const getTarget = `-- name: GetTarget :one
SELECT id, recipient_id, kind, config, enabled
FROM notification_targets
WHERE id = ?
`

func (q *Queries) GetTarget(ctx context.Context, id int64) (NotificationTargets, error) {
	row := q.db.QueryRowContext(ctx, getTarget, id)
	var i NotificationTargets
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Config,
		&i.Enabled,
	)
	return i, err
}

const listAllTargets = `-- name: ListAllTargets :many
SELECT id, recipient_id, kind, config, enabled
FROM notification_targets
ORDER BY recipient_id, id
`

// ListAllTargets is the home page's fan-out in one query rather than one per
// recipient.
func (q *Queries) ListAllTargets(ctx context.Context) ([]NotificationTargets, error) {
	rows, err := q.db.QueryContext(ctx, listAllTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTargets{}
	for rows.Next() {
		var i NotificationTargets
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledTargets = `-- name: ListEnabledTargets :many
SELECT id, recipient_id, kind, config, enabled
FROM notification_targets
WHERE recipient_id = ?
  AND enabled
ORDER BY kind
`

// ListEnabledTargets is the fan-out: one SendJob per row it returns.
func (q *Queries) ListEnabledTargets(ctx context.Context, recipientID int64) ([]NotificationTargets, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTargets, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTargets{}
	for rows.Next() {
		var i NotificationTargets
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT id, recipient_id, kind, config, enabled
FROM notification_targets
WHERE recipient_id = ?
ORDER BY kind
`

func (q *Queries) ListTargets(ctx context.Context, recipientID int64) ([]NotificationTargets, error) {
	rows, err := q.db.QueryContext(ctx, listTargets, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTargets{}
	for rows.Next() {
		var i NotificationTargets
		if err := rows.Scan(
			&i.ID,
			&i.RecipientID,
			&i.Kind,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTargetEnabled = `-- name: SetTargetEnabled :exec
UPDATE notification_targets
SET enabled = ?
WHERE id = ?
`

type SetTargetEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

func (q *Queries) SetTargetEnabled(ctx context.Context, arg SetTargetEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setTargetEnabled, arg.Enabled, arg.ID)
	return err
}

const updateTargetConfig = `-- name: UpdateTargetConfig :one
UPDATE notification_targets
SET config = ?
WHERE id = ?
RETURNING id, recipient_id, kind, config, enabled
`

type UpdateTargetConfigParams struct {
	Config string `json:"config"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateTargetConfig(ctx context.Context, arg UpdateTargetConfigParams) (NotificationTargets, error) {
	row := q.db.QueryRowContext(ctx, updateTargetConfig, arg.Config, arg.ID)
	var i NotificationTargets
	err := row.Scan(
		&i.ID,
		&i.RecipientID,
		&i.Kind,
		&i.Config,
		&i.Enabled,
	)
	return i, err
}
